# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.7.4"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box          = "windows_2016_docker"
  config.vm.communicator = "winrm"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--vram", 64]
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    v.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
    v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
  end

  ["vmware_fusion", "vmware_workstation"].each do |provider|
    config.vm.provider provider do |v, override|
      v.gui = true
      v.vmx["memsize"] = "2048"
      v.vmx["numvcpus"] = "2"
      v.vmx["vhv.enable"] = "TRUE"
      v.enable_vmrun_ip_lookup = false
    end
  end

  config.vm.provider :vcloud do |vcloud, override|
    vcloud.vapp_prefix = "windows-docker-swarm"
    vcloud.ip_subnet = "192.168.36.1/255.255.255.0" # our test subnet with fixed IP adresses for everyone
    override.vm.usable_port_range = 2200..2999
    vcloud.memory = 8192
    vcloud.cpus = 4
  end

  config.vm.define "registry" do |config|
    config.vm.hostname = "registry"
    config.vm.network :private_network, ip: "192.168.36.2", gateway: "192.168.36.1"
    config.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args: "192.168.36.2"
    config.vm.provision "shell", path: "scripts/run-registry.ps1", privileged: false
    config.vm.provision "shell", path: "scripts/run-swarm-master.ps1", privileged: false
    config.vm.provision "shell", path: "scripts/run-portainer.ps1", privileged: false
    config.vm.network :forwarded_port, guest: 3375, host: 3375, id: "swarm", auto_correct: true
    config.vm.network :forwarded_port, guest: 9000, host: 9000, id: "portainer", auto_correct: true
  end

  config.vm.define "sw-win-01" do |config|
    config.vm.hostname = "sw-win-01"
    config.vm.network :private_network, ip: "192.168.36.3", gateway: "192.168.36.1"
    config.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args: "192.168.36.3"
    config.vm.provision "shell", path: "scripts/add-registry.ps1", privileged: false
    config.vm.provision "shell", path: "scripts/run-swarm-agent.ps1", privileged: false
  end

  config.vm.define "sw-win-02" do |config|
    config.vm.hostname = "sw-win-02"
    config.vm.network :private_network, ip: "192.168.36.4", gateway: "192.168.36.1"
    config.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args: "192.168.36.4"
    config.vm.provision "shell", path: "scripts/add-registry.ps1", privileged: false
    config.vm.provision "shell", path: "scripts/run-swarm-agent.ps1", privileged: false
  end

  config.vm.define "sw-win-03" do |config|
    config.vm.hostname = "sw-win-03"
    config.vm.network :private_network, ip: "192.168.36.5", gateway: "192.168.36.1"
    config.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args: "192.168.36.5"
    config.vm.provision "shell", path: "scripts/add-registry.ps1", privileged: false
    config.vm.provision "shell", path: "scripts/run-swarm-agent.ps1", privileged: false
  end

  config.vm.define "sw-lin-01" do |config|
    config.vm.hostname     = "sw-lin-01"
    config.vm.box          = "ubuntu/xenial64"
    config.vm.communicator = "ssh"
    config.vm.network :private_network, ip: "192.168.36.6", gateway: "192.168.36.1"
    config.vm.provision "shell", path: "scripts/install-docker.sh", privileged: false
    config.vm.provision "shell", path: "scripts/run-swarm-agent.sh", privileged: false
  end
end
