# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.7.4"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box          = "windows_2016_docker"
  config.vm.communicator = "winrm"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--vram", 64]
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    v.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
    v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
  end

  ["vmware_fusion", "vmware_workstation"].each do |provider|
    config.vm.provider provider do |v, override|
      v.gui = true
      v.vmx["memsize"] = "2048"
      v.vmx["numvcpus"] = "2"
      v.vmx["vhv.enable"] = "TRUE"
      v.enable_vmrun_ip_lookup = false
    end
  end

  config.vm.define "registry" do |config|
    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--vram", 8]
    end
    config.vm.box          = "boxcutter/ubuntu1404"
    config.vm.communicator = "ssh"
    config.vm.hostname = "registry"
    config.vm.network :private_network, ip: "192.168.48.11", gateway: "192.168.48.1"
    config.vm.provision "shell", path: "scripts/install-docker.sh"
    config.vm.provision "shell", path: "scripts/run-registry.sh"
    config.vm.provision "shell", path: "scripts/run-swarm-master.sh"
  end

  config.vm.define "sw-win-01" do |config|
    config.vm.hostname = "sw-win-01"
    config.vm.network :private_network, ip: "192.168.48.21", gateway: "192.168.48.1"
    config.vm.provision "shell", path: "scripts/add-registry.ps1", privileged: false
    config.vm.provision "shell", path: "scripts/run-swarm-agent.ps1", privileged: false
  end

  config.vm.define "sw-win-02" do |config|
    config.vm.hostname = "sw-win-02"
    config.vm.network :private_network, ip: "192.168.48.22", gateway: "192.168.48.1"
    config.vm.provision "shell", path: "scripts/add-registry.ps1", privileged: false
    config.vm.provision "shell", path: "scripts/run-swarm-agent.ps1", privileged: false
  end

  config.vm.define "sw-win-03" do |config|
    config.vm.hostname = "sw-win-03"
    config.vm.network :private_network, ip: "192.168.48.23", gateway: "192.168.48.1"
    config.vm.provision "shell", path: "scripts/add-registry.ps1", privileged: false
    config.vm.provision "shell", path: "scripts/run-swarm-agent.ps1", privileged: false
  end
end
