# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "windows_10_insider_14352"
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

  config.vm.communicator = "winrm"

  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  config.vm.guest = :windows
  config.windows.halt_timeout = 15

#  config.vm.provision "shell", path: "provision.ps1", privileged: false
  config.vm.provision "shell", path: "scripts/install-container-feature.ps1", privileged: true #, powershell_elevated_interactive: true
  config.vm.provision "shell", path: "scripts/enable-autologon.ps1", privileged: true
  config.vm.provision "reload"
  config.vm.provision "shell", path: "scripts/install-docker.ps1", privileged: true
  config.vm.provision "shell", path: "scripts/install-base-container-images.ps1", privileged: true, powershell_elevated_interactive: true
  config.vm.provision "shell", path: "scripts/add-docker-group.ps1", privileged: true
  config.vm.provision "reload"

  ["vmware_fusion", "vmware_workstation"].each do |provider|
    config.vm.provider provider do |v, override|
      v.gui = true
    end
  end

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["gui.fitguestusingnativedisplayresolution"] = "TRUE"
    v.vmx["mks.enable3d"] = "TRUE"
    v.vmx["mks.forceDiscreteGPU"] = "TRUE"
    v.vmx["gui.fullscreenatpoweron"] = "TRUE"
    v.vmx["gui.viewmodeatpoweron"] = "fullscreen"
    v.vmx["gui.lastPoweredViewMode"] = "fullscreen"
    v.vmx["sound.startconnected"] = "TRUE"
    v.vmx["sound.present"] = "TRUE"
    v.vmx["sound.autodetect"] = "TRUE"
    v.enable_vmrun_ip_lookup = false
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
    v.vmx["vhv.enable"] = "TRUE"
  end
end
